config/routes.rb
Rails.application.routes.draw do

  resources :patients do
    collection do
      get :graph
    end
  end

  get 'doctors/index'
  get 'receptionists/index'
  root "patients#index"

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/Validatable.rb
module Validatable
	extend ActiveSupport::Concern

	included do 
		validates :name, presence: true
	end
end

app/models/doctor.rb
class Doctor < User
    has_many :patients, foreign_key: 'user_id'
end

app/models/patient.rb
class Patient < ApplicationRecord

  # concern for validation
  include Validatable

  belongs_to :doctor, class_name: 'User', foreign_key: 'user_id'

end

app/models/receptionist.rb
class Receptionist < User
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

 	# concern for validation
	include Validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include PatientsHelper

    before_action :set_current_user

    private
  
    def set_current_user
      @current_user = User.find_by(id: session[:user_id])
    end
end

app/controllers/concerns/Authentication.rb
module Authentication
 	extend ActiveSupport::Concern

 	included do 
 		before_action :authenticate_user
 	end

	private

	def authenticate_user
	  unless @current_user
	    redirect_to login_path, alert: 'Please log in'
	  end
	end
end

app/controllers/concerns/Geek.rb
module Geek
	def geeks 
		puts "This is only for testing extend and include"
	end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController

	#concern is using 
	include Authentication

  def index
  	puts self.class.geeks
    @doctor = User.find_by(id: @current_user)
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  #concern is using 
  include Authentication

  def index
    if @current_user.type.eql?("Doctor")
      @user = User.find_by(id: @current_user.id)
      @patients = @user.patients
    else
      @patients = Patient.all
    end
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.create(patient_params)
    if @patient.valid?
      CrudNotificationMailer.create(@patient).deliver_now
      flash[:errors] = 'Created Successfully'
      redirect_to patients_path
    else
      flash[:errors] = @patient.errors.full_messages
      render :new
    end
  end

  def show
    @patient = Patient.find(params[:id])
  end

  def edit
    @patient = Patient.find(params[:id])
  end

  def update
    @patient = Patient.find(params[:id])
    if @patient.update(patient_params)
      flash[:errors] = 'Updated Successfully'
      redirect_to patient_path(@patient)
    else
      flash[:errors] = @patient.errors.full_messages
      redirect_to edit_patient_path
    end
  end

  def destroy
    @patient = Patient.find(params[:id])
    if @patient.delete
      flash[:errors] = 'Deleted Successfully'
      redirect_to root_path(@patient)
    else
      flash[:errors] = @patient.errors.full_messages
      redirect_to destroy_patient_path
    end
  end
  def graph
    @patients_by_day = Patient.group_by_day(:created_at).count
  end
  private
  def patient_params
    params.require(:patient).permit(:name, :gender, :age, :description, :user_id)
  end
end

app/controllers/receptionists_controller.rb
class ReceptionistsController < ApplicationController

	#concern is using 
	include Authentication

  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      if user.type.eql?("Doctor")
        redirect_to doctors_index_path
      else
        redirect_to receptionists_index_path
      end
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path, notice: 'Logged out successfully'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
	def dateformat(date)
		date.strftime("%B %-d, %Y")
	end
end

app/helpers/receptionists_helper.rb
module ReceptionistsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/doctors/index.html.erb
<h1>Doctor Portal</h1>
<h3> <%= "Hello #{@doctor.name}"%><h3>
<%= link_to "View Patient", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CRUD</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

    <!--Bootstrap CDN  -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  <body>
    <%= yield %>
  </body>
</html>

app/views/patients/_doc.html.erb
<div class="flex-column" style = "height: auto;">
  <h1> Patient List </h1>

  <% if flash[:errors] %>
    <% flash.each do |name,message| %>
      <p class="text-danger"><%= message%></p>
    <% end %>
  <% end %>

  <div>
    <table class="table table-info table-striped">
      <ol class="fs-2">
        <thead class="table-secondary">
            <td class="text-center"> Id </td>
            <td class="text-center"> Name </td>
            <td class="text-center"> Age </td>
            <td class="text-center"> Gender </td>
            <td class="text-center"> Description </td>
            <td class="text-center"> Registration date </td>
            <td colspan=3 class="text-center"> Action </td>
        </thead>
        <% @patients.each do |e| %>
          <tr>
            <td class="text-center"> <%= e.id %> </td>
            <td class="text-center"> <%= link_to e.name, patient_path(e) %> </td>
            <td class="text-center"> <%= e.age %> </td>
            <td class="text-center"> <%= e.gender %> </td>
            <td class="text-center"> <%= e.description %> </td>
            <td class="text-center"> <%= dateformat(e.created_at) %> </td>  <!-- helper is calling  -->

            <td class="text-center"><%= button_to "Show",patient_path(e),method: :get, class:"btn-success border-0 rounded-pill shadow px-3 py-2" %></td>
            <td class="text-center"><%= button_to "Delete",patient_path(e),method: :delete, class:"btn-danger border-0 rounded-pill shadow px-3 py-2" %></td>
          </tr>
        <% end %>
      </ol>
    </table>
  </div>
  <div class="text-center mt-3">
    <%= button_to "View Patient Registration Graph", graph_patients_path, method: :get, class: "btn btn-primary" %>
  </div>
</div>

app/views/patients/_recep.html.erb
<div class="flex-column" style = "height: auto;">
<h1> Patient List </h1>

<% if flash[:errors] %>
  <% flash.each do |name,message| %>
    <p class="text-danger"><%= message%></p>
  <% end %>
<% end %>

<div>
  <table class="table table-info table-striped">
    <ol class="fs-2">
      <thead class="table-secondary">
        <td class="text-center"> Id </td>
        <td class="text-center"> Name </td>
        <td class="text-center"> Age </td>
        <td class="text-center"> Gender </td>
        <td class="text-center"> Description </td>
        <td colspan=3 class="text-center"> Action </td>
      </thead>
      <% @patients.each do |e| %>
        <tr>
          <td class="text-center"> <%= e.id %> </td>
          <td class="text-center"> <%= link_to e.name, patient_path(e) %> </td>
          <td class="text-center"> <%= e.age %> </td>
          <td class="text-center"> <%= e.gender %> </td>
          <td class="text-center"> <%= e.description %> </td>

          <td class="text-center"><%= button_to "Show",patient_path(e),method: :get, class:"btn-success border-0 rounded-pill shadow px-3 py-2" %></td>
          <td class="text-center"><%= button_to "Edit",edit_patient_path(e),method: :get, class:"btn-primary border-0 rounded-pill shadow px-3 py-2" %></td>
          <td class="text-center"><%= button_to "Delete",patient_path(e),method: :delete, class:"btn-danger border-0 rounded-pill shadow px-3 py-2" %></td>
        </tr>
      <% end %>
    </ol>
  </table>
</div>
<div class="d-flex">
  <%= button_to "Add New Patient", new_patient_path, method: :get ,class:"btn-warning border-0 rounded-pill shadow p-3 m-3" %>
</div>
</div>

app/views/patients/edit.html.erb
<div class="flex-column">
  <div class="card shadow" style="width: 36rem;">
    <div class="card-header">
      <h2 class="text-center">Patient Form</h2>
    </div>
    <div class="card-body">
      
      <% if flash[:errors] %>
        <% flash[:errors].each do |error| %>
          <p class="text-danger"><%= error %></p>
        <% end %>
      <% end %>
      
      <%= form_with model: @patient do |f| %>
        <%= f.label :name, "Patient Name :", class:"mt-3" %>
        <%= f.text_field :name, placeholder: "Enter Patient's Name",class:"mb-2 form-control" %>
        <br>
        
        <div class="form-group">
          <%= f.label :age %>
          <%= f.number_field :age, placeholder: "Patient's Age", class:"mb-2 form-control", min: 0 %>
        </div>
        <br>

        <div class="form-group">
          <%= f.label "Gender :" %>
          <%= f.radio_button :gender, "male" %>
          <%= f.label :gender, "Male" %>
          <%= f.radio_button :gender, "female" %>
          <%= f.label :gender, "Female" %>
        </div>
        <br>

        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, placeholder: "Enter Patient's Description",class:"mb-2 form-control", min: 0 %>
        </div>
        <br>
        <%= f.submit "Save Patient", class:"btn-primary border-0 rounded-pill shadow p-3" %>
      <% end %>
    </div>
  </div>
</div>

app/views/patients/graph.html.erb
<div class="flex-column" style="height: auto;">
  <h1> Patient Registration Graph </h1>
  <div>
    <%= line_chart @patients_by_day, library: { scales: { xAxes: [{ type: 'time', time: { unit: 'day' } }] } } %>
  </div>
  <%= button_to "View all Patients", patients_path,method: :get ,class:"btn-primary border-0 rounded-pill shadow p-2 m-2" %>
</div>

app/views/patients/index.html.erb
<% if @current_user.present?%>

  <% if @current_user.type.eql?("Doctor")%>
    <%= render partial: "patients/doc" %>
  <% else %>
    <%= render partial: "patients/recep" %>
  <% end %>

  <%= link_to "Log Out", logout_path %>

<% else %>
  <%= link_to "Log In", login_path %>
<% end %>

app/views/patients/new.html.erb
<div class="flex-column">
  <div class="card shadow" style="width: 36rem;">
    <div class="card-header">
      <h2 class="text-center">Patient Form</h2>
    </div>
    <div class="card-body">
      
      <% if flash[:errors] %>
        <% flash[:errors].each do |error| %>
          <p class="text-danger"><%= error %></p>
        <% end %>
      <% end %>
      
      <%= form_with model: @patient do |f| %>
        <%= f.label :name, "Patient Name :", class:"mt-3" %>
        <%= f.text_field :name, placeholder: "Enter Patient's Name",class:"mb-2 form-control" %>
        <br>
        
        <div class="form-group">
          <%= f.label :age %>
          <%= f.number_field :age, placeholder: "Patient's Age", class:"mb-2 form-control", min: 0 %>
        </div>
        <br>

        <div class="form-group">
          <%= f.label "Gender :" %>
          <%= f.radio_button :gender, "male" %>
          <%= f.label :gender, "Male" %>
          <%= f.radio_button :gender, "female" %>
          <%= f.label :gender, "Female" %>
        </div>
        <br>

        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, placeholder: "Enter Patient's Description",class:"mb-2 form-control", min: 0 %>
        </div>
        <br>

        <div class="form-group">
          <%= f.collection_select :user_id, Doctor.all, :id, :name, { prompt: 'Select Doctor' }, class:"mb-2 form-control" %>
        </div>

        <%= f.submit "Save Patient", class:"btn-primary border-0 rounded-pill shadow p-3" %>
      <% end %>
    </div>
  </div>
</div>

app/views/patients/show.html.erb
<div class="flex-column" style="height:100vh;">

  <% if flash[:errors] %>
    <% flash.each do |name,message| %>
      <p class="text-danger"><%= message%></p>
    <% end %>
  <% end %>

  <div class="d-flex">
    <div class="m-5" >
      <div class="card bg-light border-warning shadow">
        <div class="card-body">
          <div class="card-header">
            <h2 class="text-center">Patient's Details</h2>
          </div>
          <div>
            <h2> &#10145; ID: <%= @patient.id %> </h2>
            <h2> &#10145; Name: <%= @patient.name %> </h2>
            <h2> &#10145; Name: <%= @patient.age %> </h2>
            <h2> &#10145; Gender: <%= @patient.gender %> </h2>
            <h2> &#10145; Hobbies: <%= @patient.description %> </h2>
          </div>
          <div class="d-flex">
            <%= button_to "Edit Patient" , edit_patient_path, method: :get ,class:"btn-success border-0 rounded-pill shadow p-2 m-2" %>
            <%= button_to "Delete Patient", patient_path, method: :delete ,class:"btn-danger border-0 rounded-pill shadow p-2 m-2" %>
            <%= button_to "View all Patients", patients_path,method: :get ,class:"btn-primary border-0 rounded-pill shadow p-2 m-2" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/receptionists/index.html.erb
<h1>receptionist Portal</h1>
<%= link_to "View Patient", root_path %>